// <auto-generated />
namespace ParrotWIngs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfield_TransactionsresultingBalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfield_TransactionsresultingBalance));
        
        string IMigrationMetadata.Id
        {
            get { return "201609020439092_newfield_Transactions-resultingBalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
